language: python

python:
  - 3.6

env:
  - DOCKER_COMPOSE_VERSION=1.23.2 COMPOSE_FILE=docker-compose.yml:docker-compose.override.yml:docker-compose.test.yml CERYX_DISABLE_LETS_ENCRYPT=true

install:
  - pip install --upgrade --ignore-installed docker-compose==${DOCKER_COMPOSE_VERSION}
  - docker-compose build

services:
  - redis-server
  - docker

script:
  - docker-compose up -d
  - docker-compose run api ./bin/test
  - docker-compose run test

addons:
  apt:
    packages:
      - docker-ce

notifications:
  email: false
