version: '3.5'

services:
  ceryx:
    image: sourcelair/ceryx:v0.1.2
    ports:
      - ${CERYX_EXTERNAL_PORT:-80}:80
      - ${CERYX_EXTERNAL_SSL_PORT:-443}:443
    environment:
      CERYX_REDIS_HOST: ${CERYX_REDIS_HOST:-redis}
      CERYX_REDIS_PORT: ${CERYX_REDIS_PORT:-6379}
      CERYX_SSL_CERT: /run/secrets/public-urls.crt
      CERYX_SSL_CERT_KEY: /run/secrets/public-urls.key
      CERYX_DISABLE_LETS_ENCRYPT: 'true'
    secrets:
      - public-urls.crt
      - public-urls.key

  api:
    image: sourcelair/ceryx-api:latest
    environment:
      CERYX_REDIS_HOST: ${CERYX_REDIS_HOST:-redis}
      CERYX_REDIS_PORT: ${CERYX_REDIS_PORT:-6379}
      CERYX_API_HOST: ${CERYX_API_HOST:-0.0.0.0}
      CERYX_API_PORT: ${CERYX_API_PORT:-5555}
      CERYX_API_HOSTNAME: ${CERYX_API_HOSTNAME:-localhost}
      CERYX_DEBUG: ${CERYX_DEBUG:-false}

  redis:
    image: redis:3.2.11-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

networks:
  default:
    attachable: true
    driver: overlay
    name: ceryx

secrets:
  public-urls.crt:
    name: ceryx-public-urls-bundle-v1
    external: true
  public-urls.key:
    name: ceryx-public-urls-key-v1
    external: true

volumes:
  redis_data:

