version: '3.7'

services:
  ceryx:
    build: ./ceryx
    volumes:
      - ./ceryx/nginx/conf:/usr/local/openresty/nginx/conf
      - ./ceryx/nginx/lualib:/usr/local/openresty/nginx/lualib
      - ./ceryx/static:/etc/ceryx/static
    environment:
      CERYX_DEBUG: ${CERYX_DEBUG:-true}
      CERYX_DOCKERIZE_EXTRA_ARGS: ""

  api:
    build: ./api
    volumes:
      - ./api:/opt/ceryx
    environment:
      CERYX_API_HOSTNAME: ${CERYX_API_HOSTNAME:-api.ceryx.dev}
      CERYX_DEBUG: ${CERYX_DEBUG:-true}

networks:
  default:
    driver: bridge  # Use a Bridge network for local development
    name: ceryx
