version: '3.5'

services:
  test:
    build:
      context: ./ceryx
      dockerfile: Dockerfile.test
    environment:
      CERYX_API_URL: "http://api:${CERYX_API_PORT:-5555}"
    volumes:
      - ./ceryx:/usr/src/app
    depends_on:
      - ceryx
      - api
