version: '3.5'

services:
  ceryx:
    build: ./ceryx
    volumes:
      - ./ceryx/nginx/conf:/usr/local/openresty/nginx/conf
      - ./ceryx/nginx/lualib:/usr/local/openresty/nginx/lualib
      - ./ceryx/nginx/sites-enabled:/usr/local/openresty/nginx/sites-enabled

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        PIP_REQUIREMENTS_FILE: requirements-dev.txt
    volumes:
      - ./api:/opt/ceryx
    environment:
      CERYX_API_HOSTNAME: ${CERYX_API_HOSTNAME:-api.ceryx.dev}
      CERYX_DEBUG: ${CERYX_DEBUG:-true}

networks:
  default:
    attachable: true
    driver: bridge  # Use a Bridge network for local development
    name: ceryx
